name: Daily RSS to Posts

on:
  schedule:
    - cron: '0 22 * * *'   # JST 07:00（UTC 22:00）
  workflow_dispatch:        # 手動実行ボタンも有効化

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate posts from RSS
        run: |
          python scripts/rss_to_posts.py
      - name: Commit & push if changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: auto-generate posts $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes"
          fi
